module.exports = {
  plugins: ['react'],
  rules: {
    'react/function-component-definition': ['error', { namedComponents: 'function-expression' }],
    // 'react-hooks/exhaustive-deps': 'error',
    // 'react/button-has-type': 'off',
    // 'react/default-props-match-prop-types': 'error',
    // 'react/destructuring-assignment': 'off',
    // 'react/forbid-prop-types': 'warn',
    // 'react/jsx-filename-extension': 'warn',
    // 'react/jsx-pascal-case': 'error',
    // 'react/jsx-props-no-spreading': 'off',
    // 'react/no-access-state-in-setstate': 'error',
    // 'react/no-array-index-key': 'warn',
    // 'react/no-danger': 'error',
    // 'react/no-find-dom-node': 'off',
    // 'react/no-unused-state': 'error',
    // 'react/prefer-stateless-function': 'off',
    'react/require-default-props': 'off',
    // 'react/sort-comp': 'off',
    // 'react/state-in-constructor': 'off',
    // 'react/static-property-placement': 'off',
  },
};
