/* eslint-disable */
// prettier-ignore
// This file is automatically generated by typings-for-css-modules.
// Don't change it directly!

declare namespace StylesMcssNamespace {
  export interface IStylesMcss {
    'root': string;
  }
}

declare const StylesMcssModule: StylesMcssNamespace.IStylesMcss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesMcssNamespace.IStylesMcss;
};

export = StylesMcssModule;
